### ISSUE TITLE
Dollar sign character appears as named HTML entity ("&dollar;" instead of "$") in email to self

### ISSUE THREAD

**Issue by dsnielsen** [susom/redcap-em-giftcard-reward#6]
![image](https://user-images.githubusercontent.com/128075056/225694850-b8f15758-9134-4652-9bf1-4697e2c4ae4e.png)
When respondent's email their reward code to themselves, the body of the email shows the named HTML entity instead of dollar sign character ("$"). Only affects emails in which the respondent elects to have their code emailed to them - the initial email and the reward landing page work fine however.

**Comment by 123andy** [comment]
I think I've fixed this with the next release to go out...
