### ISSUE TITLE
How to place text after the reward link in the notification email body

### ISSUE THREAD

**Issue by eval-edwards** [susom/redcap-em-giftcard-reward#7]
I hope all is well. This is a great module. My REDCap is showing version 1.1.0. How do we update it? 
![image](https://github.com/susom/redcap-em-giftcard-reward/assets/136846031/30259bf7-5d76-4ae1-949d-ec4d02887bc1)

Is there a way to place text after the reward link in the external module instead of before it when editing for configuration of the module’s Reward Notification Email Body field? 
Is it possible for people to edit the module and would Python be needed or CSS to do it? 

Thanks

**Comment by 123andy** [comment]
There are releases to version 3.1. https://github.com/susom/redcap-em-giftcard-reward/releases
It is up to your REDCap site admin to upgrade/update external modules.

I'm not sure about the location -- whatever the UI supports.  If you need more functionality to the rendering you could potentially submit a PR.

**Comment by eval-edwards** [comment]
Thank you for this reply. What is a PR?

**Comment by 123andy** [comment]
Sorry.  A PR is a pull request - a way for a GitHub user to recommend an update to a program.
________________________________

**Comment by eval-edwards** [comment]
How do I make a pull request? It is greyed out. Is there a way for me to email my suggested changes?


![Pull request issue](https://github.com/susom/redcap-em-giftcard-reward/assets/136846031/797c30d4-0d1f-447c-ba9b-1128efc90c81)
